      - postgres
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - personality_network

  # Frontend (React)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: personality_frontend
    environment:
      REACT_APP_API_URL: http://localhost:5000
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - personality_network

volumes:
  postgres_data:

networks:
  personality_network:
    driver: bridge